//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langulag.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientDetails
    {
        public string ФИО { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public Nullable<decimal> Возраст { get; set; }
        public Nullable<int> Количество_тегов { get; set; }
        public string пол { get; set; }
        public Nullable<System.DateTime> Дата_последнего_посещения { get; set; }
    }
}
